### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by davisonio** [kirsle/follow-sync#2]
Thanks for this great script, I'm using it on a smaller account of mine but when I try it on a bigger account I get this error:
```
2017/03/06 10:33:46 Beginning the data collection process...
2017/03/06 10:33:46 Collecting your 'Followers' list
panic: unexpected end of JSON input

goroutine 1 [running]:
github.com/kirsle/follow-sync/src.(*App).getFollowers(0xc42004df18)
	/Users/craig/go/src/github.com/kirsle/follow-sync/src/insta.go:30 +0x251
github.com/kirsle/follow-sync/src.(*App).Run(0xc42004df18)
	/Users/craig/go/src/github.com/kirsle/follow-sync/src/app.go:45 +0xf3
main.main()
	/Users/craig/go/src/github.com/kirsle/follow-sync/main.go:23 +0x1aa
```

**Comment by kirsle** [comment]
This looks like an upstream issue in [github.com/ahmdrz/goinsta](https://github.com/ahmdrz/goinsta); my code just panics with the error message given by their API [here](https://github.com/kirsle/follow-sync/blob/4e12f45949b1ddd0e2c4c994f95a41f0c1c8e7b4/src/insta.go#L28-L31).

**Comment by davisonio** [comment]
Ah I see, I'll open an error there then.
