### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by certainlyjacked** [kirsle/follow-sync#5]
Unfortunately I get the following error message:

panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x632360, 0xc04200c040)
        /usr/lib/golang/src/runtime/panic.go:500 +0x1af
github.com/ahmdrz/goinsta.(*Instagram).Login(0xc0420336c0, 0xe, 0xc04200d0c0)
        /home/kirsle/go/src/github.com/ahmdrz/goinsta/goinsta.go:126 +0xaea
github.com/kirsle/follow-sync/src.(*App).login(0xc04206beb8)
        /home/kirsle/go/src/github.com/kirsle/follow-sync/src/app.go:78 +0x15a
github.com/kirsle/follow-sync/src.(*App).Run(0xc04206beb8)
        /home/kirsle/go/src/github.com/kirsle/follow-sync/src/app.go:40 +0x47
main.main()
        /home/kirsle/go/src/github.com/kirsle/follow-sync/main.go:23 +0x1bb
Press any key to continue . . .

I've deleted the database and run the script again, without success.
Can you help me out?

**Comment by kirsle** [comment]
[Version 0.2.0](https://github.com/kirsle/follow-sync/releases/tag/v0.2.0) should fix this bug by updating the upstream dependency on [ahmdrz/goinsta](https://github.com/ahmdrz/goinsta).
